### ISSUE TITLE
Failed To Start

### ISSUE THREAD

**Issue by DaniSVG** [beat-saber-modding-group/BeatSaberModInstaller#52]
I tried running the mod manager but it didn't start. It gave me this error:

![Screenshot (226)](https://user-images.githubusercontent.com/50109874/56902424-93482f00-6a9a-11e9-9dc9-b9b1e7b45253.png)

I'm not good with stuff like that and I honestly don't know what went wrong? I've used it before and it worked fine back then. Can someone help me? Thx in advance!

**Comment by megalon** [comment]
Can you try this new build?
[BeatSaberModManager.zip](https://github.com/beat-saber-modding-group/BeatSaberModInstaller/files/3128911/BeatSaberModManager.zip)


I think I've found the bug here, but I'm not sure how the library path wouldn't contain any valid drive letters. Do you have the game installed on an external hard drive?
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/blob/5c499273b3555a17df6d572847e23f40321a72a2/BeatSaberModManager/Core/PathLogic.cs#L149

Branch for this build if anyone is interested 
https://github.com/beat-saber-modding-group/BeatSaberModInstaller/tree/oculus-path-detect-fix

**Comment by DaniSVG** [comment]
> Can you try this new build?
> [BeatSaberModManager.zip](https://github.com/beat-saber-modding-group/BeatSaberModInstaller/files/3128911/BeatSaberModManager.zip)
> 
> I think I've found the bug here, but I'm not sure how the library path wouldn't contain any valid drive letters. Do you have the game installed on an external hard drive?
> https://github.com/beat-saber-modding-group/BeatSaberModInstaller/blob/5c499273b3555a17df6d572847e23f40321a72a2/BeatSaberModManager/Core/PathLogic.cs#L149
> 
> Branch for this build if anyone is interested
> https://github.com/beat-saber-modding-group/BeatSaberModInstaller/tree/oculus-path-detect-fix

Wow thank you so much, that one worked! And answering your question, no Beat Saber is just installed on my D drive.
